# 1 ИМПОРТЫ НЕОБХОДИМЫХ БИБЛОТЕК И ЗАГРУЗКА ДАННЫХ

In [1351]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [1352]:
GDP_growth = pd.read_csv("../data/API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_121708.csv", skiprows=4) # will seperate to Zambia and China
exports = pd.read_csv("../data/API_NE.EXP.GNFS.CD_DS2_en_csv_v2_3934.csv", skiprows=4)
FDI_inflows = pd.read_csv("../data/API_NE.EXP.GNFS.CD_DS2_en_csv_v2_3934.csv", skiprows = 4)
exchange_rate = pd.read_csv("../data/API_PA.NUS.FCRF_DS2_en_csv_v2_121619.csv", skiprows=4)
external_debt = pd.read_csv("../data/API_20_DS2_en_csv_v2_39106.csv", skiprows=4)
copper_prices = pd.read_excel("../data/CMO-Historical-Data-Annual.xlsx", sheet_name = "Annual Prices (Nominal)", skiprows=6)

# 2 VARIABLE PREP

## 2.1 GDP_Zambia // GDP_china

In [1353]:
GDP_growth.tail()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
261,Kosovo,XKX,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.825656,3.406632,4.756801,-5.340275,10.745656,4.278499,4.067627,4.573097,NaN,NaN
262,"Yemen, Rep.",YEM,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-5.071796,0.752448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,3.844734,6.177931,7.373709,7.939609,6.122798,...,1.157947,1.556784,0.259936,-6.168918,4.858649,2.058137,0.806105,0.534844,NaN,NaN
264,Zambia,ZMB,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,1.361382,-2.490839,3.272393,12.214048,16.647456,...,3.525863,4.034494,1.441306,-2.785055,6.234922,5.211224,5.367943,3.820048,NaN,NaN
265,Zimbabwe,ZWE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,6.316157,1.434471,6.244345,-1.106172,4.910571,...,4.734411,5.009922,-6.332450,-7.816951,8.468017,6.139263,5.350869,1.742395,NaN,NaN

In [1354]:
GDP_Zambia = GDP_growth[GDP_growth["Country Code"] == "ZMB"]
GDP_China = GDP_growth[GDP_growth["Country Name"] == "China"]

In [1355]:
GDP_China.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
40,China,CHN,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,-27.27,-5.58,10.3,18.18,16.95,...,6.891266,6.756718,6.068502,2.340188,8.570085,3.134189,5.414843,4.977357,NaN,NaN

Exclude Irrelevant columns

In [1356]:
GDP_China.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', '2025', 'Unnamed: 70'],
      dtype='str')

In [1357]:
GDP_Zambia.drop(labels=["Country Name", "Country Code", "Indicator Code", "Unnamed: 70"], axis=1, inplace=True)
GDP_China.drop(labels=["Country Name", "Country Code", "Indicator Code", "Unnamed: 70"], axis=1, inplace=True)

In [1358]:
GDP_Zambia.head()

,Indicator Name,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
264,GDP growth (annual %),NaN,1.361382,-2.490839,3.272393,12.214048,16.647456,-5.57031,7.919697,1.24833,...,3.7551,3.525863,4.034494,1.441306,-2.785055,6.234922,5.211224,5.367943,3.820048,NaN

In [1359]:
GDP_Zambia = GDP_Zambia.T
GDP_China = GDP_China.T

In [1360]:
GDP_Zambia.head()

                                  264
Indicator Name  GDP growth (annual %)
1960                              NaN
1961                         1.361382
1962                        -2.490839
1963                         3.272393

In [1361]:
GDP_China.head()

                                   40
Indicator Name  GDP growth (annual %)
1960                              NaN
1961                           -27.27
1962                            -5.58
1963                             10.3

Make first row headers

In [1362]:
new_header = GDP_Zambia.iloc[0] # grab the first row for the header
GDP_Zambia = GDP_Zambia[1:] # take the data less the header row
GDP_Zambia.columns = new_header
# GDP_Zambia.reset_index(drop = True, inplace=True)
new_header = GDP_China.iloc[0] # grab the first row for the header
GDP_China = GDP_China[1:] # take the data less the header row
GDP_China.columns = new_header

In [1363]:
GDP_Zambia.head()

Indicator Name GDP growth (annual %)
1960                             NaN
1961                        1.361382
1962                       -2.490839
1963                        3.272393
1964                       12.214048

In [1364]:
GDP_Zambia.columns

Index(['GDP growth (annual %)'], dtype='object', name='Indicator Name')

In [1365]:
GDP_Zambia.reset_index(inplace=True)
GDP_Zambia.rename({
        'index': 'Year',
    'GDP growth (annual %)': 'ZMB GDP growth (annual %)'
}, axis=1, inplace=True)

GDP_China.reset_index(inplace=True)
GDP_China.rename({
    'index': 'Year',
    'GDP growth (annual %)': 'CHN GDP growth (annual %)'
}, axis=1, inplace=True)

In [1366]:
GDP_China.head()

Indicator Name  Year CHN GDP growth (annual %)
0               1960                       NaN
1               1961                    -27.27
2               1962                     -5.58
3               1963                      10.3
4               1964                     18.18

In [1367]:
GDP_Zambia.head()

Indicator Name  Year ZMB GDP growth (annual %)
0               1960                       NaN
1               1961                  1.361382
2               1962                 -2.490839
3               1963                  3.272393
4               1964                 12.214048

In [1368]:
GDP_China.head()

Indicator Name  Year CHN GDP growth (annual %)
0               1960                       NaN
1               1961                    -27.27
2               1962                     -5.58
3               1963                      10.3
4               1964                     18.18

## 2.2 Exports

In [1369]:
exports.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,Exports of goods and services (current US$),NE.EXP.GNFS.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.153472e+09,2.241203e+09,2.232927e+09,1.324111e+09,1.945183e+09,2.686049e+09,3.159820e+09,3.582826e+09,NaN,NaN
1,Africa Eastern and Southern,AFE,Exports of goods and services (current US$),NE.EXP.GNFS.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.329367e+11,2.588136e+11,2.455958e+11,2.095170e+11,2.880277e+11,3.334846e+11,3.084462e+11,3.198254e+11,NaN,NaN
2,Afghanistan,AFG,Exports of goods and services (current US$),NE.EXP.GNFS.CD,2.222223e+07,2.444446e+07,26666680.0,6.888892e+07,7.111114e+07,113333340.0,...,NaN,NaN,NaN,2.079571e+09,2.045190e+09,2.664600e+09,2.890630e+09,NaN,NaN,NaN
3,Africa Western and Central,AFW,Exports of goods and services (current US$),NE.EXP.GNFS.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,Exports of goods and services (current US$),NE.EXP.GNFS.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.148003e+10,3.244471e+10,3.000118e+10,1.858315e+10,3.138583e+10,4.618152e+10,3.464337e+10,3.179802e+10,NaN,NaN

In [1370]:
exports.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', '2025', 'Unnamed: 70'],
      dtype='str')

In [1371]:
exports = exports[exports["Country Code"]== "ZMB"]

In [1372]:
exports.drop(labels=["Country Name", "Country Code", "Indicator Code", "Unnamed: 70"], axis=1, inplace=True)

In [1373]:
exports.head()

,Indicator Name,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
264,Exports of goods and services (current US$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.403491e+09,9.053912e+09,9.987165e+09,8.073235e+09,8.473998e+09,1.153788e+10,1.172209e+10,1.126453e+10,8.851528e+09,NaN

Transpose the dataset

In [1374]:
exports = exports.T

In [1375]:
new_header = exports.iloc[0] # grab the first row for the header
exports = exports[1:] # take the data less the header row
exports.columns = new_header

In [1376]:
exports.head()

Indicator Name Exports of goods and services (current US$)
1960                                                   NaN
1961                                                   NaN
1962                                                   NaN
1963                                                   NaN
1964                                                   NaN

## 2.3 FDI inflows

In [1377]:
FDI_inflows.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,Exports of goods and services (current US$),NE.EXP.GNFS.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.153472e+09,2.241203e+09,2.232927e+09,1.324111e+09,1.945183e+09,2.686049e+09,3.159820e+09,3.582826e+09,NaN,NaN
1,Africa Eastern and Southern,AFE,Exports of goods and services (current US$),NE.EXP.GNFS.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.329367e+11,2.588136e+11,2.455958e+11,2.095170e+11,2.880277e+11,3.334846e+11,3.084462e+11,3.198254e+11,NaN,NaN
2,Afghanistan,AFG,Exports of goods and services (current US$),NE.EXP.GNFS.CD,2.222223e+07,2.444446e+07,26666680.0,6.888892e+07,7.111114e+07,113333340.0,...,NaN,NaN,NaN,2.079571e+09,2.045190e+09,2.664600e+09,2.890630e+09,NaN,NaN,NaN
3,Africa Western and Central,AFW,Exports of goods and services (current US$),NE.EXP.GNFS.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,Exports of goods and services (current US$),NE.EXP.GNFS.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.148003e+10,3.244471e+10,3.000118e+10,1.858315e+10,3.138583e+10,4.618152e+10,3.464337e+10,3.179802e+10,NaN,NaN

In [1378]:
FDI_inflows.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', '2025', 'Unnamed: 70'],
      dtype='str')

In [1379]:
FDI_inflows = FDI_inflows[FDI_inflows['Country Code'] == "ZMB"]

In [1380]:
FDI_inflows.drop(labels=["Country Name", "Country Code", "Indicator Code", "Unnamed: 70"], axis=1, inplace=True)

In [1381]:
FDI_inflows = FDI_inflows.T

In [1382]:
new_header = FDI_inflows.iloc[0] # grab the first row for the header
FDI_inflows = FDI_inflows[1:] # take the data less the header row
FDI_inflows.columns = new_header

## 2.4 EXCHANGE RATE

In [1383]:
exchange_rate = exchange_rate[exchange_rate["Country Code"] == "ZMB"]

In [1384]:
exchange_rate.drop(labels=["Country Name", "Country Code", "Indicator Code", "Unnamed: 70"], axis=1, inplace=True)

In [1385]:
exchange_rate = exchange_rate.T

In [1386]:
new_header = exchange_rate.iloc[0]
exchange_rate = exchange_rate[1:]
exchange_rate.columns = new_header

In [1387]:
exchange_rate.head()

Indicator Name Official exchange rate (LCU per US$, period average)
1960                                                     0.714286
1961                                                     0.714286
1962                                                     0.714286
1963                                                     0.714286
1964                                                     0.714286

## 2.5 ВНЕШНИЙ ДОЛГ

In [1388]:
external_debt[(external_debt["Indicator Name"] == "External debt stocks (% of GNI)") & (external_debt["Country Code"] == "ZMB") ]

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
16155,Zambia,ZMB,External debt stocks (% of GNI),DT.DOD.DECT.GN.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,96.006154,95.025133,128.346607,167.518099,133.551637,103.673946,110.675742,114.201909,NaN,NaN

In [1389]:
external_debt = external_debt[(external_debt["Indicator Name"] == "External debt stocks (% of GNI)") & (external_debt["Country Code"] == "ZMB") ]
external_debt.drop(labels=["Country Name", "Country Code", "Indicator Code", "Unnamed: 70"], axis=1, inplace=True)

In [1390]:
external_debt.head(10)

,Indicator Name,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
16155,External debt stocks (% of GNI),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,77.571432,96.006154,95.025133,128.346607,167.518099,133.551637,103.673946,110.675742,114.201909,NaN

In [1391]:
external_debt = external_debt.T

In [1392]:
new_header = external_debt.iloc[0]
external_debt = external_debt[1:]
external_debt.columns = new_header

In [ ]:
external_debt.head()

Indicator Name External debt stocks (% of GNI)
1960                                       NaN
1961                                       NaN
1962                                       NaN
1963                                       NaN
1964                                       NaN

## 2.6 Copper prices

In [ ]:
copper_prices.columns

Index(['Unnamed: 0', 'Crude oil, average', 'Crude oil, Brent',
       'Crude oil, Dubai', 'Crude oil, WTI', 'Coal, Australian',
       'Coal, South African', 'Natural gas, US', 'Natural gas, Europe',
       'Liquefied natural gas, Japan', 'Natural gas index', 'Cocoa',
       'Coffee, Arabica', 'Coffee, Robusta', 'Tea, avg 3 auctions',
       'Tea, Colombo', 'Tea, Kolkata', 'Tea, Mombasa', 'Coconut oil',
       'Groundnuts', 'Fish meal', 'Groundnut oil', 'Palm oil',
       'Palm kernel oil', 'Soybeans', 'Soybean oil', 'Soybean meal', 'Barley',
       'Maize', 'Sorghum', 'Rice, Thai 5% ', 'Rice, Thai 25% ',
       'Rice, Thai A.1', 'Rice, Viet Namese 5%', 'Wheat, US SRW',
       'Wheat, US HRW', 'Banana, Europe', 'Banana, US', 'Orange', 'Beef',
       'Chicken', 'Lamb **', 'Shrimps, Mexican', 'Sugar, EU', 'Sugar, US',
       'Sugar, world', 'Tobacco, US import u.v.', 'Logs, Cameroon',
       'Logs, Malaysian', 'Sawnwood, Cameroon', 'Sawnwood, Malaysian',
       'Plywood', 'Cotton, A Index', 'Rubber, TSR20 **', 'Rubber, RSS3',
       'Phosphate rock', 'DAP', 'TSP', 'Urea ', 'Potassium chloride',
       'Aluminum', 'Iron ore, cfr spot', 'Copper', 'Lead', 'Tin', 'Nickel',
       'Zinc', 'Gold', 'Platinum', 'Silver'],
      dtype='str')

In [ ]:
copper_prices.rename({
    'Unnamed: 0':'Year',
    'Copper': 'Copper ($/mt)'
}, axis=1, inplace=True) # axis = 1 so pandas knows we're renaming cols

In [ ]:
copper_prices.head()

,Year,"Crude oil, average","Crude oil, Brent","Crude oil, Dubai","Crude oil, WTI","Coal, Australian","Coal, South African","Natural gas, US","Natural gas, Europe","Liquefied natural gas, Japan",...,Aluminum,"Iron ore, cfr spot",Copper ($/mt),Lead,Tin,Nickel,Zinc,Gold,Platinum,Silver
0,NaN,($/bbl),($/bbl),($/bbl),($/bbl),($/mt),($/mt),($/mmbtu),($/mmbtu),($/mmbtu),...,($/mt),($/dmtu),($/mt),($/mt),($/mt),($/mt),($/mt),($/troy oz),($/troy oz),($/troy oz)
1,1960.0,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,511.471832,11.42,678.755833,198.85,2196.733333,1631,246.191667,35.27,83.5,0.9137
2,1961.0,1.57,1.57,1.57,…,…,…,0.15,0.404774,…,...,511.471832,11.02,633.084167,176.975,2449.891667,1711,214.308333,35.25,83.5,0.924442
3,1962.0,1.52,1.52,1.52,…,…,…,0.16,0.404774,…,...,498.060392,11.01,645.143333,155.283333,2471.383333,1761,185.925,35.23,83.5,1.083725
4,1963.0,1.5,1.5,1.5,…,…,…,0.16,0.391351,…,...,498.795265,11.02,645.950833,174.808333,2507.733333,1741.666667,211.508333,35.09,80.930833,1.279108

In [ ]:
copper_prices.dtypes

Year                  float64
Crude oil, average     object
Crude oil, Brent       object
Crude oil, Dubai       object
Crude oil, WTI         object
                       ...
Nickel                 object
Zinc                   object
Gold                   object
Platinum               object
Silver                 object
Length: 70, dtype: object

Commented out the year filter Because we will need to filter in the combined dataset

In [ ]:
copper_prices = copper_prices[["Year", "Copper ($/mt)"]]
# copper_prices = copper_prices[(copper_prices["Year"] >= 1999) & (copper_prices["Year"] <= 2023)] # use bitwise and/or for series

In [ ]:
copper_prices.head()

     Year Copper ($/mt)
0     NaN        ($/mt)
1  1960.0    678.755833
2  1961.0    633.084167
3  1962.0    645.143333
4  1963.0    645.950833

In [ ]:
copper_prices.reset_index(drop = True, inplace=True)

In [ ]:
copper_prices.head()

     Year Copper ($/mt)
0     NaN        ($/mt)
1  1960.0    678.755833
2  1961.0    633.084167
3  1962.0    645.143333
4  1963.0    645.950833